export default [
  {
    id: 785,
    versionFlag: 0,
    titleCh: "首页",
    titleEn: "home page",
    titleFlag: 0,
    path: "/timeline",
    pathMobile: "/mobile/home",
    icon: null,
    type: "CARD",
    description: "测试",
    state: 0,
    sort: 1,
    iconFlag: 0,
    parentId: 0,
    children: [],
    typeId: null
  },
  {
    id: 786,
    versionFlag: 0,
    titleCh: "關於我們",
    titleEn: "About us",
    titleFlag: 0,
    path: "/about",
    pathMobile: "/mobile/mobile-aboutUs",
    icon: null,
    type: "CARD",
    description: null,
    state: 0,
    sort: 2,
    iconFlag: 0,
    parentId: 0,
    children: [
      {
        id: null,
        versionFlag: 0,
        titleCh: "關於矩陣縱橫",
        titleEn: "About matrix design",
        titleFlag: 0,
        path: "/aboutUs?position=culture",
        pathMobile: "/mobile/mobile-aboutUs?position=culture",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 2,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "發展歷程",
        titleEn: "History",
        titleFlag: 0,
        path: "/aboutUs?position=course",
        pathMobile: "/mobile/mobile-aboutUs?position=course",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 3,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "主要合作夥伴",
        titleEn: "Partners",
        titleFlag: 0,
        path: "/aboutUs?position=cooperation",
        pathMobile: "/mobile/mobile-aboutUs?position=cooperation",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 4,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "獎項榮譽",
        titleEn: "Honors",
        titleFlag: 0,
        path: "/aboutUs?position=achievement",
        pathMobile: "/mobile/mobile-aboutUs?position=achievement",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 5,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      }
    ],
    typeId: null
  },
  {
    id: 787,
    versionFlag: 0,
    titleCh: "服務範圍",
    titleEn: "Service",
    titleFlag: 0,
    path: "/services",
    pathMobile: "/mobile/mobile-server",
    icon: null,
    type: "CARD",
    description: null,
    state: 0,
    sort: 3,
    iconFlag: 0,
    parentId: 0,
    children: [
      {
        id: null,
        versionFlag: 0,
        titleCh: "設計領域",
        titleEn: "Design field",
        titleFlag: 0,
        path: "/services?position=sjly",
        pathMobile: "/mobile/mobile-server?position=sjly",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 2,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "創意增值",
        titleEn: "Creative value-added services",
        titleFlag: 0,
        path: "/services?position=cyfz",
        pathMobile: "/mobile/mobile-server?position=cyfz",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 3,
        iconFlag: 0,
        parentId: null,
        children: null,
        typeId: null
      }
    ],
    typeId: null
  },
  {
    id: 788,
    versionFlag: 0,
    titleCh: "項目案例",
    titleEn: "Project",
    titleFlag: 0,
    path: "/cases",
    pathMobile: "/mobile/mobile-cases",
    icon: null,
    type: "TYPE",
    description: null,
    state: 0,
    sort: 4,
    iconFlag: 0,
    parentId: 0,
    children: [
      {
        id: null,
        versionFlag: 0,
        titleCh: "住宅人居",
        titleEn: "Residence",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=0",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 1,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1171
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "辦公公共",
        titleEn: "Office public",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=1",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 2,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1172
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "酒店度假",
        titleEn: "Hotel Resort",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=2",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 3,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1173
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "文化教育",
        titleEn: "Cultural & Education",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=3",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 4,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1174
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "康養醫美",
        titleEn: "Health Care",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=4",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 5,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1175
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "商業零售",
        titleEn: "Commercial",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=5",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 6,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1176
      },
      {
        id: null,
        versionFlag: 0,
        titleCh: "舊建築改造",
        titleEn: "Renovation",
        titleFlag: 0,
        path: "/cases",
        pathMobile: "/mobile/mobile-cases?position=6",
        icon: null,
        type: null,
        description: null,
        state: null,
        sort: 7,
        iconFlag: null,
        parentId: null,
        children: null,
        typeId: 1177
      }
    ],
    typeId: null
  },
  {
    id: 789,
    versionFlag: 0,
    titleCh: "研發課題",
    titleEn: "R&D",
    titleFlag: 0,
    path: "/topic",
    pathMobile: "/mobile/mobile-topic",
    icon: null,
    type: "CARD",
    description: null,
    state: 0,
    sort: 5,
    iconFlag: 0,
    parentId: 0,
    children: [],
    typeId: null
  },
  {
    id: 790,
    versionFlag: 0,
    titleCh: "新聞媒體",
    titleEn: "News",
    titleFlag: 0,
    path: "/news",
    pathMobile: "/mobile/mobile-news",
    icon: null,
    type: "CARD",
    description: null,
    state: 0,
    sort: 6,
    iconFlag: 0,
    parentId: 0,
    children: [],
    typeId: null
  },
  {
    id: 791,
    versionFlag: 0,
    titleCh: "聯係我們",
    titleEn: "Contact us",
    titleFlag: 0,
    path: "/contact",
    pathMobile: "/mobile/mobile-contact",
    icon: null,
    type: "PAGE",
    description: null,
    state: 0,
    sort: 7,
    iconFlag: 0,
    parentId: 0, 
    typeId: null
  }
]
